import type { Metadata } from "next";
import { Inter, Space_Mono, VT323 } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });
const vt323 = VT323({ subsets: ["latin"], weight: '400', variable: "--font-vt323" });
const spacemono = Space_Mono({ subsets: ["latin"], weight: '400', variable: "--font-spacemono" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, vt323.variable, spacemono.variable, "dark")}>
        <Header />
        {children}
      </body>
    </html>
  );
}
